import Head from "next/head";
import { useState } from "react";

export async function getServerSideProps() {
  const result = await fetch("https://jsonplaceholder.typicode.com/photos");
  const data = await result.json();
  const slicedArray = data.slice(0, 100);
  return {
    props: {
      posts: slicedArray,
    },
  };
}

export default function Home({ posts }: any) {
  const [allImages, setAllImages]: any = useState(posts);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        style={{
          display: "flex",
          height: "100vh",
          width: "100vw",
          flexWrap: "wrap",
        }}
      >
        {allImages.map((image: any) => (
          <div key={image.id} style={{ maxWidth: "200px", height: "auto" }}>
            <p>albumId: {image.albumId}</p>
            <p>Id: {image.id}</p>
            <p>Title: {image.title}</p>
            {/* <img style={{ maxWidth: "100%" }} src={image.url} alt="img" /> */}
          </div>
        ))}
      </div>
    </>
  );
}
