import Head from "next/head";
import Link from "next/link";
import { useState } from "react";

export default function Race({ race }: any) {
  const [allRace, setAllRace] = useState(race);
  return (
    <>
      <Head>
        <title>Race Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link href="/">Home</Link>

      <div
        style={{
          display: "flex",
          height: "100vh",
          width: "100vw",
          flexWrap: "wrap",
        }}
      >
        {allRace.map((image: any) => (
          <div key={image.id} style={{ maxWidth: "200px", height: "auto" }}>
            <p>albumId: {image.albumId}</p>
            <p>Id: {image.id}</p>
            <p>Title: {image.title}</p>
            {/* <img style={{ maxWidth: "100%" }} src={image.url} alt="img" /> */}
          </div>
        ))}
      </div>
    </>
  );
}
Race.getInitialProps = async function () {
  const result = await fetch("https://jsonplaceholder.typicode.com/photos");
  const data = await result.json();
  return {
    race: data,
  };
};
